\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
    \usepackage{xltxtra,xunicode}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\ErrorTok}[1]{\textbf{{#1}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={Diego Aviles},
            pdftitle={3.3 Illustration of the productConfig package},
            colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\setcounter{secnumdepth}{0}

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{3.3 Illustration of the productConfig package}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{Diego Aviles}
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  \predate{\centering\large\emph}
  \postdate{\par}
  \date{2016-05-05}



\begin{document}

\maketitle


\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

First, let us look at the data:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{tail.matrix}\NormalTok{(camera_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       cid usid round atid   selected selectable
## 1823 1835   62     1    4 0.01944444          1
## 1824 1836   62     2    4 0.16805556          1
## 1825 1837   63     0    1 1.00000000          2
## 1826 1838   63     0    2 1.00000000          1
## 1827 1839   63     0    3 1.00000000          1
## 1828 1840   63     0    4 0.16805556          1
\end{verbatim}

As you can see our data displays 1828 rows with around 63 different
users in a rather complex format which makes it practically difficult to
work with. This is the reason we need the basic function cluster
\texttt{GetFunctions}. For example, it is quite necessary to know how
many attributes there are in out data:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{get_attrs_ID}\NormalTok{(}\DataTypeTok{dataset=}\NormalTok{camera_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1 2 3 4
\end{verbatim}

Given that our functions are mostly vectorized and assuming all users
have the same attribtues, we can ask for the unique values of each
\texttt{attr}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{getAttrValues}\NormalTok{(}\DataTypeTok{dataset=}\NormalTok{camera_data, }\DataTypeTok{attr =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{lapply}\NormalTok{(temp, unique)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`1`
## [1] 3 0 2 1
## 
## $`2`
## [1] 0 3 2 1
## 
## $`3`
## [1] 0 3 2 1
## 
## $`4`
## [1]  0.16805556 -0.27777778 -0.12916667  0.01944444  0.46527778  0.31666667
## [7]  0.61388889
\end{verbatim}

Now that we know how many attributes there are, we also know how many
columns the decision matrices are going to have. The number of rows
depends on how much each user interacted with the product configurator
and again, since functions are vectorised we can calculate the number of
rows for all users using \texttt{getRoundsById}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all.rounds <-}\StringTok{ }\KeywordTok{getRoundsById}\NormalTok{(camera_data, }\DataTypeTok{userid =} \KeywordTok{getAllUserIds}\NormalTok{(camera_data))}
\KeywordTok{head}\NormalTok{(all.rounds, }\DecValTok{3}\NormalTok{) }\CommentTok{# To display only the results for the first three users}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`6`
##   [1]  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
##  [24] 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45
##  [47] 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68
##  [70] 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
##  [93] 92 93 94 95 96 97 98 99
## 
## $`9`
## [1] 0 1 2 3
## 
## $`10`
## [1] 0 1 2 3 4
\end{verbatim}

We can now easily observe that user 10 interacted four times with the
configurator four times before making a decision.

The three functions presented above are necessary to create more complex
structures, such as the decision matrix. To build it, we just need to
use the right function with the right parameters. At mentioned earlier,
the fourth parameter \texttt{attr=4} is price, which means it is a cost
attribute (lower values are better). To handle this we input the
correspondent attribute ID in \texttt{cost\_ids}. Choosing any random
user from our table, we calculate its decision matrix.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{decisionMatrix}\NormalTok{(camera_data, }\DecValTok{33}\NormalTok{, }\DataTypeTok{rounds=}\StringTok{"all"}\NormalTok{, }\DataTypeTok{cost_ids=}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`33`
##        attr1 attr2 attr3       attr4
## 0round     1     1     1 -0.16805556
## 1round     1     1     2 -0.01944444
## 2round     1     0     2 -0.16805556
## 3round     2     0     2 -0.01944444
## 4round     1     0     2 -0.16805556
## 5round     1     0     3 -0.01944444
\end{verbatim}

Notice how we did not specify the \texttt{attr} argument. As suggested
before, aside from \texttt{dataset} and \texttt{userid} almost all
arguments have a default value and perform a default behavior. When no
input is entered \texttt{attr} calculates using all recognized
attributes and \texttt{rounds} with the first and the last, which is why
we explicitly specified \texttt{"all"}. Our next step is to determine
the reference points. For the \texttt{refps} of PT we will use the
default settings of user \texttt{33} which are:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{decisionMatrix}\NormalTok{(camera_data, }\DecValTok{33}\NormalTok{, }\DataTypeTok{rounds=}\StringTok{"first"}\NormalTok{, }\DataTypeTok{cost_ids=}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`33`
##        attr1 attr2 attr3      attr4
## 0round     1     1     1 -0.1680556
\end{verbatim}

This result should correspond to and validate our PT-reference-point
function \texttt{referencePoints}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{referencePoints}\NormalTok{(camera_data, }\DecValTok{33}\NormalTok{, }\DataTypeTok{cost_ids=}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`33`
##       rp 1       rp 2       rp 3       rp 4 
##  1.0000000  1.0000000  1.0000000 -0.1680556
\end{verbatim}

Now that we have determined the decision matrix and the reference points
for user 33, we can proceed to compute the following steps.

{[}Insert quick figure{]}

However, since we have demonstrated how the functions build on each
other and to avoid repetitiveness, we will calculate these matrices
using only one function.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pvMatrix}\NormalTok{(camera_data, }\DecValTok{33}\NormalTok{, }\DataTypeTok{attr=}\DecValTok{1}\NormalTok{:}\DecValTok{4}\NormalTok{, }\DataTypeTok{rounds=}\StringTok{"all"}\NormalTok{, }\DataTypeTok{cost_ids =} \DecValTok{4}\NormalTok{,}
         \DataTypeTok{alpha =} \FloatTok{0.88}\NormalTok{, }\DataTypeTok{beta=}\FloatTok{0.88}\NormalTok{, }\DataTypeTok{lambda=}\FloatTok{2.25}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`33`
##        attr1 attr2     attr3        attr4
## 0round     0  0.00 0.0000000 0.000000e+00
## 1round     0  0.00 0.5433674 1.000000e+00
## 2round     0 -2.25 0.5433674 2.129512e-12
## 3round     1 -2.25 0.5433674 1.000000e+00
## 4round     0 -2.25 0.5433674 2.129512e-12
## 5round     0 -2.25 1.0000000 1.000000e+00
\end{verbatim}

Finally, for the final step of calculating the overall prospect values,
we need to determine the attribute weights using the
\texttt{WeightFunctions} cluster. Within it we have three weighting
functions to our disposal, each mirroring a method described in section
\ref{ch:Content1:sec:Section3}:
\texttt{differenceToIdeal, entropy, highAndStandard}. Using the entropy
method we first need to normalize the \emph{decision matrix} and pass it
on to the respective function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{norm.DM33 <-}\StringTok{ }\KeywordTok{normalize.sum}\NormalTok{(decisionMatrix33[[}\DecValTok{1}\NormalTok{]])}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{entropy}\NormalTok{(norm.DM33)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     attr1     attr2     attr3     attr4 
## 0.1962875 0.3616283 0.1962424 0.2458418
\end{verbatim}

Since most functions are vectorialized, they return a list. For this
reason, we use \texttt{[[1]]} to subset the matrix from the list, which
can be then passed on to \texttt{normalize.sum}. Keeping such details in
mind in addition to having to know which normalizing function to use
with each weight method can be quite unefficient. Alternatively, we can
computate the above results with an `interface' function called
\texttt{weight.entropy}, which also functions for the above functions,
with their corresponding names.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{weight.entropy}\NormalTok{(camera_data, }\DecValTok{33}\NormalTok{, }\DataTypeTok{attr=}\DecValTok{1}\NormalTok{:}\DecValTok{4}\NormalTok{, }\DataTypeTok{rounds=}\StringTok{"all"}\NormalTok{, }\DataTypeTok{cost_ids =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`33`
##     attr1     attr2     attr3     attr4 
## 0.1962875 0.3616283 0.1962424 0.2458418
\end{verbatim}

The weight vector reflects the relative importance each attribute has
for the user, thus its addition results in 1. Furthermore, each row of
the value matrix represents how much value one specific product setting
(or product alternative) represents to the user, relative to its
reference points. Multiplying each row of the value matrix with the
weight vector, returns the overall prospect value of each alternative.
To achieve this we can find at least two equivalent ways.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{overallPV}\NormalTok{(camera_data, }\DecValTok{33}\NormalTok{, }\DataTypeTok{rounds=}\StringTok{"all"}\NormalTok{, }\DataTypeTok{cost_ids =} \DecValTok{4}\NormalTok{, }\DataTypeTok{weightFUN =}\StringTok{"entropy"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{overallPV}\NormalTok{(camera_data, }\DecValTok{33}\NormalTok{, }\DataTypeTok{rounds=}\StringTok{"all"}\NormalTok{, }\DataTypeTok{cost_ids =} \DecValTok{4}\NormalTok{, }\DataTypeTok{weightFUN =}\StringTok{"entropy"}\NormalTok{,}
          \DataTypeTok{alpha=}\FloatTok{0.88}\NormalTok{, }\DataTypeTok{beta=}\FloatTok{0.88}\NormalTok{, }\DataTypeTok{lambda=}\FloatTok{2.25}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`33`
##     0round     1round     2round     3round     4round     5round 
##  0.0000000  0.3524735 -0.7070319 -0.2649027 -0.7070319 -0.3715795
\end{verbatim}

The last command illustrates many of the implementation principles
described in section \ref{ch:Content2:sec:Section2}. The function
\texttt{overallPV} functions without the user having to calculate
something first (a). It is build upon many of the functions we used
before as you can notice by the many shared parameters it contains (b).
It calculates our final results with just one command (c) and it does so
by returning a list (e). Throughout this demonstration we also showed
how some functions are vectorized in the \texttt{userid} parameter (d)
and how they handle cost type attributes by using the \texttt{cost\_ids}
argument.

Lastly, ranking alternatives by the highest value reveals that the
second alternative showed the highest \emph{prospect value} for user 33.
This is quite interesting, since the chosen product configuration,
i.e.~the last round has a value of -0.3715795, which is not even the
second highest option. Nevertheless, we made three important assumptions
which influence our results: (1) the default values as reference points,
(2) prospect theory's assumptions and value function and (3) the entropy
weighting function.

The overall prospect values for the DRP approach and the TRP theory can
be achieved in a similar manner with \texttt{overallDRP} and
\texttt{overallTRP}. As mentioned before for multiple reference point
approaches there is no theoretical framework on how to read all the
reference points from the data. Thus, for DRP and TRP we need to specify
\texttt{SQ, G} and \texttt{MR, SQ, G} for each of the four attributes.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dualPoints <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DataTypeTok{sq=}\FloatTok{1.5}\NormalTok{,}\DataTypeTok{g=}\FloatTok{2.5}\NormalTok{,  }\FloatTok{1.5}\NormalTok{,}\FloatTok{2.5}\NormalTok{,  }\FloatTok{1.5}\NormalTok{,}\FloatTok{2.5}\NormalTok{,  }\FloatTok{0.17}\NormalTok{,-}\FloatTok{0.10}\NormalTok{),}
                     \DataTypeTok{nrow=}\DecValTok{4}\NormalTok{, }\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{, }\DataTypeTok{byrow=}\OtherTok{TRUE}\NormalTok{)}
\NormalTok{triPoints <-}\StringTok{  }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DataTypeTok{mr=}\FloatTok{0.5}\NormalTok{,}\DataTypeTok{sq=}\FloatTok{1.5}\NormalTok{,}\DataTypeTok{g=}\FloatTok{2.5}\NormalTok{,  }\FloatTok{0.5}\NormalTok{,}\FloatTok{1.5}\NormalTok{,}\FloatTok{2.5}\NormalTok{,  }\FloatTok{0.5}\NormalTok{,}\FloatTok{1.5}\NormalTok{,}\FloatTok{2.5}\NormalTok{,  }
                       \FloatTok{0.40}\NormalTok{,}\FloatTok{0.17}\NormalTok{,-}\FloatTok{0.10}\NormalTok{), }\DataTypeTok{nrow=}\DecValTok{4}\NormalTok{, }\DataTypeTok{ncol=}\DecValTok{3}\NormalTok{, }\DataTypeTok{byrow=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

For the fourth attribute we chose a smaller G than the the SQ and the MR
(MR only for TRP), since it will be converted to a benefit type
attribute. Furthermore, since attributes 1 to 3 have the same possible
values, they should have the same reference points. Now we can calculate
the overall prospect values for user 33. For simplicity, we will use the
default values for DRP and TRP (see pages 14, 15).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{overallDRP}\NormalTok{(camera_data, }\DecValTok{33}\NormalTok{, }\DataTypeTok{rounds=}\StringTok{"all"}\NormalTok{, }\DataTypeTok{cost_ids =} \DecValTok{4}\NormalTok{, }\DataTypeTok{weightFUN=}\StringTok{"entropy"}\NormalTok{,}
           \DataTypeTok{dual.refps =} \NormalTok{dualPoints, }\DataTypeTok{lambda =} \FloatTok{2.25}\NormalTok{, }\DataTypeTok{delta =} \FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`33`
##      0round      1round      2round      3round      4round      5round 
## -0.38710408  0.11688393 -0.67236180  0.08821309 -0.67236180 -0.31466703
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{overallTRP}\NormalTok{(camera_data, }\DecValTok{33}\NormalTok{, }\DataTypeTok{rounds=}\StringTok{"all"}\NormalTok{, }\DataTypeTok{cost_ids =} \DecValTok{4}\NormalTok{, }\DataTypeTok{weightFUN=}\StringTok{"entropy"}\NormalTok{,}
           \DataTypeTok{tri.refps =} \NormalTok{triPoints, }\DataTypeTok{beta_f =} \DecValTok{5}\NormalTok{,}\DataTypeTok{beta_l =} \DecValTok{1}\NormalTok{,}\DataTypeTok{beta_g =} \DecValTok{1}\NormalTok{,}\DataTypeTok{beta_s =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`33`
##       0round       1round       2round       3round       4round 
## -0.379069320 -0.005574333 -1.333125943 -0.697884278 -1.333125943 
##       5round 
## -0.763388519
\end{verbatim}

The weighting functions are easier to use, since they basically require
the same information. Analogous to\texttt{entropy}, we use the same
arguments to call our two other weight functions.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{weight.differenceToIdeal}\NormalTok{(camera_data, }\DecValTok{33}\NormalTok{, }\DataTypeTok{attr=}\DecValTok{1}\NormalTok{:}\DecValTok{4}\NormalTok{, }\DataTypeTok{rounds=}\StringTok{"all"}\NormalTok{, }\DataTypeTok{cost_ids =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`33`
##     attr1     attr2     attr3     attr4 
## 0.1558442 0.1948052 0.3896104 0.2597403
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{weight.highAndStandard}\NormalTok{(camera_data, }\DecValTok{33}\NormalTok{, }\DataTypeTok{attr=}\DecValTok{1}\NormalTok{:}\DecValTok{4}\NormalTok{, }\DataTypeTok{rounds=}\StringTok{"all"}\NormalTok{, }\DataTypeTok{cost_ids =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`33`
##         1         2         3         4 
## 0.2252364 0.1761044 0.2788773 0.3197819
\end{verbatim}

The goal of this chapter was solely to introduce and familiarize the
reader with the mechanics and parameters of `productConfig'. Now that we
know\ldots{} we would like to shortly illustrate how we can use
productConfig together with visualizing packages to gain interesting
insights into product configurators. Consider\ldots{}

\end{document}
